#!/bin/bash

echo maven-project > /tmp/.auth
echo $BUILD_TAG >> /tmp/.auth
echo $PASS >> /tmp/.auth

scp -i /home/karthik/docker/jenkins-pipeline/ubuntu-key /tmp/.auth karthik@192.168.55.104:/tmp/.auth
